
function GetSportList() {
    return [
    ["Basketball, University of Texas Longhorns", "https://www.texreview.com/2018/01/university-of-texas-longhorns-womens.html"],
    ["Longhorn Run", "https://www.texreview.com/2018/04/longhorn-run-2018-in-austin-texas.html"],
    ["Cirque du Soleil Crystal", "https://www.texreview.com/2018/02/cirque-du-soleil-crystal-at-heb-center.html"],

    ["Football, Austin Acoustics Tryouts", "https://www.texreview.com/2017/12/austin-acoustic-tryouts-at-austin.html"],
    ["Football, Austin Acoustics Training Camp", "https://www.texreview.com/2017/12/first-day-of-austin-acoustic-training.html"],
    ["Football, Austin Wild", "http://www.texreview.com/2018/04/austin-wild-at-heb-center-in-cedar-park.html"],

    ["MMA, Strike League Championship", "https://www.texreview.com/2017/04/strike-league-mma-fighting-championship.html"],
    ["MMA, Strike League SL2 Rumble at the Rock", "https://www.texreview.com/2017/08/strike-league-sl2-rumble-at-rock.html"],

    ["Motorsports, FIA World Endurance Championship", "https://www.texreview.com/2017/09/spirit-of-le-mans-fia-world-endurance.html"],
    ["Motorsports, Lucas Oil Drag Boat Race", "https://www.texreview.com/2017/08/top-fuel-hydro-at-lucas-oil-drag-boat.html"],
    ["Motorsports, Pirelli World Challenge", "https://www.texreview.com/2017/09/pirelli-world-challenge-sprintx-at.html"],
    ["Motorsports, Radical North American Masters", "https://www.texreview.com/2017/09/radical-north-american-masters-at.html"],

    ["Mountain Bike, Pro USA Mens", "https://www.texreview.com/2014/03/mens-pro-usa-cycling-mountain-bike-race.html"],
    ["Mountain Bike, Pro USA Womens", "http://www.texreview.com/2014/03/womens-pro-usa-cycling-mountain-bike.html"],

    ["Wrestling, WW", "https://www.texreview.com/2018/03/wwe-live-road-to-wrestlemania-at-heb_29.html"],
    ["Wrestling, WWE NXT", "http://www.texreview.com/2018/03/wwe-live-road-to-wrestlemania-at-heb_29.html"],
    ["Wrestling, WWE NXT", "https://www.texreview.com/2017/11/wwe-presents-nxt-live-at-heb-center-in_38.html"],

    ["Volleyball, AVP Professional Beach", "https://www.texreview.com/2018/05/avp-pro-beach-volleyball-tour-crowns.html"],
    ["Volleyball, North Carolina State Wolfpack", "https://www.texreview.com/2017/12/north-carolina-state-wolfpack.html"],
    ["Volleyball, Oregon State Beavers", "https://www.texreview.com/2017/12/oregon-state-beavers-volleyball-match.html"],
    ["Volleyball, University of Texas Longhorns", "http://www.texreview.com/2017/09/university-of-texas-longhorn-volleyball.html"],
    ["Volleyball, Texas A&M Aggies", "http://www.texreview.com/2018/04/texas-aggies-volleyball-match-against.html"],

    ["X Games", "https://www.texreview.com/2015/08/x-games-austin-texas-june-4-7-2015.html"],
    ["Various school football, basketball, volleyball, track, other", ""],
    ];
}

function GetFestList() {
    return [
    ["Austin City Limits Music Festival", ""],
    ["Botanica Music Festival", ""],
    ["Fiesta Oyster Bake", "https://www.texreview.com/2017/04/fiesta-oyster-bake-at-st-marys.html"],
    ["Free Press Summer Fest (FPSF)", "http://www.texreview.com/2017/06/free-press-summer-festival-fpsf-2017-in.html"],
    ["Fun Fun Fun Fest", ""],
    ["ILLectric River Music and Art Experience", "https://www.texreview.com/2018/06/illectric-river-music-and-art.html"],
    ["Luck Reunion", "https://www.texreview.com/2018/03/luck-reunion-music-festival-2018-in.html"],
    ["River City Rockfest", "http://www.texreview.com/2017/05/river-city-rockfest-at-at-center-in-san.html"],
    ["Mayhem Festival", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Utopia Fest", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-friday-2014.html"],
    ["Vans Warped Tour", "https://www.texreview.com/2017/07/vans-warped-tour-2017.html"],
    ];
}

function GetBandList() {
    return [
    ["2Cellos", "https://www.texreview.com/2018/01/2cellos-performing-at-frank-erwin.html"],

    ["A Day To Remember", "https://www.texreview.com/2016/07/a-day-to-remember-performing-at-at.html"],
    ["Abi Ann", "https://www.texreview.com/2016/11/abi-ann-performing-in-houston-texas.html"],
    ["Above My Enemy", ""],
    ["Adelitas Way", "https://www.texreview.com/2017/04/adelitas-way-performing-at-fiesta.html"],
    ["All Sides Equal", "https://www.texreview.com/2015/03/all-sides-equal-fitzgeralds-san-antonio.html"],
    ["Allie X", "https://www.texreview.com/2018/05/allie-x-performing-at-emos-austin-in.html"],
    ["AFI (A Fire Inside)", "https://www.texreview.com/2017/02/afi-performing-in-austin-texas.html"],
    ["AJ Lehrman", "https://www.texreview.com/2016/05/aj-lehrman-performing-in-austin-texas.html"],
    ["Alice Cooper", "https://www.texreview.com/2015/02/alice-cooper-majestic-theater-san.html"],
    ["alt-j", "https://www.texreview.com/2017/11/alt-j-performing-at-acl-live-moody.html"],
    ["Amon Amarth", ""],
    ["Anthony Russo", "http://www.texreview.com/2018/02/anthony-russo-performing-at-acl-live.html"],
    ["Andy Black", ""],
    ["Annalise Emerick", ""],
    ["Apocalyptica", "https://www.texreview.com/2018/05/apocalyptica-performing-at-emos-in.html"],
    ["Ashley Cleveland", ""],
    ["Ashley Monical", ""],
    ["Asleep at the Wheel", ""],
    ["Avatar", "https://www.texreview.com/2018/01/avatar-performing-at-aztec-theatre-in.html"],
    ["Avenged Sevenfold", "http://www.texreview.com/2017/06/avenged-sevenfold-performing-at.html"],

    ["Barb Wire Dolls", ""],
    ["Barton Hills Choir", ""],
    ["Bastian Baker", "https://www.texreview.com/2018/06/bastian-baker-performing-at-frank-erwin.html"],
    ["Beartooth", ""],
    ["Being As An Ocean", ""],
    ["Benjamin Booker", ""],
    ["Benji Hughes", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Billy Joe Shaver", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Black Heart Saints", "https://www.texreview.com/2017/04/black-heart-saints-performing-at-fiesta.html"],
    ["Black Label Society", ""],
    ["Black Lips", ""],
    ["Black Pistol Fire", ""],
    ["Black Rebel Motorcycle Club", "https://www.texreview.com/2018/05/black-rebel-motorcycle-club-performing.html"],
    ["Black Stone Cherry", "https://www.texreview.com/2016/07/black-stone-cherry-performing-in-cedar.html"],
    ["Blake Richardson Band", ""],
    ["Blessthefall", ""],
    ["blink-182", "https://www.texreview.com/2016/07/blink-182-performing-in-san-antonio.html"],
    ["Blue, The Misfit", ""],
    ["Blue October", "https://www.texreview.com/2016/12/blue-october-performing-in-cedar-park.html"],
    ["Borrisokane", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Boston", "https://www.texreview.com/2016/06/boston-performing-in-austin-texas.html"],
    ["Bowling For Soup", ""],
    ["Breaking Benjamin", "https://www.texreview.com/2016/03/breaking-benjamin-performing-in-austin.html"],
    ["Breakout", ""],
    ["Brent Cowles", "https://www.texreview.com/2018/05/brent-cowles-performing-at-stubbs.html"],
    ["Bret Michaels", "https://www.texreview.com/2018/04/bret-michaels-performing-at-fiesta.html"],
    ["Broods", ""],
    ["Bullet For My Valentine", "https://www.texreview.com/2015/10/bullet-for-my-valentine-austin-texas.html"],
    ["Butcher Babies", ""],

    ["Calvin Harris", ""],
    ["Canvas People", ""],
    ["Capital Cities", ""],
    ["Carnifex", ""],
    ["Carolyn Wonderland", ""],
    ["Catfish And The Bottlemen", "http://www.texreview.com/2017/09/catfish-and-bottlemen-performing-at-at.html"],
    ["Celeste'al Descent", ""],
    ["Chapel", "https://www.texreview.com/2017/04/chapel-performing-at-acl-live-theater.html"],
    ["Charlie Pierce", ""],
    ["Chris Castaneda Project", ""],
    ["Chromeo", ""],
    ["Chvrches", ""],
    ["Cilantro Boombox", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["City and Colour", ""],
    ["CNCO", "http://www.texreview.com/2017/06/cnco-performing-at-at-center-in-san.html"],
    ["CO-OP", "http://www.texreview.com/2017/10/co-op-performing-at-rock-box-in-san.html"],
    ["Code Orange", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Company of Thieves", "http://www.texreview.com/2018/02/company-of-thieves-performing-at-acl.html"],
    ["Communion", ""],
    ["Counterparts", ""],
    ["Courtney Barnett", ""],
    ["Crooks", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Cults", ""],
    ["CKY", ""],

    ["Dave Sebree", ""],
    ["Deftones", "https://www.texreview.com/2017/06/deftones-performing-at-austin360.html"],
    ["Del Castillo", ""],
    ["Demi Lovato", "https://www.texreview.com/2016/09/demi-lovato-performing-in-san-antonio.html"],
    ["Demitasse", "https://www.texreview.com/2017/02/demitasse-performing-in-san-antonio_2.html"],
    ["Dennis DeYoung Music of Styx", "https://www.texreview.com/2018/06/dennis-deyoung-and-music-of-styx.html"],
    ["Depeche Mode", "https://www.texreview.com/2018/05/depeche-mode-performing-at-at-center-in.html"],
    ["DevilDriver", "https://www.texreview.com/2016/05/devildriver-performing-in-san-antonio.html"],
    ["Disturbed", "https://www.texreview.com/2016/05/disturbed-performing-in-san-antonio.html"],
    ["Dokken", "https://www.texreview.com/2017/03/dokken-performing-in-san-antonio-texas.html"],
    ["Doll Skin", "http://www.texreview.com/2017/10/doll-skin-performing-at-the-rock-box-in.html"],
    ["Don Felder", "http://www.texreview.com/2017/07/don-felder-performing-at-heb-center-at.html"],
    ["Drowning Pool", "https://www.texreview.com/2018/04/drowning-pool-performing-at-fiesta.html"],

    ["Evanescence", "https://www.texreview.com/2016/11/evanescence-performing-in-austin-texas.html"],
    ["Emily Wolfe", ""],
    ["Emmure", ""],
    ["Enrique Iglesias", "https://www.texreview.com/2017/06/enrique-iglesias-performing-at-at.html"],
    ["Eric Hutchinson", "https://www.texreview.com/2015/09/eric-hutchinson-austin-texas-august-29.html"],
    ["Eric Tessmer", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Exodus", ""],
    ["Eye of Time", ""],
    ["Eyes Set To Kill", "https://www.texreview.com/2016/04/eyes-set-to-kill-in-san-antonio-texas.html"],

    ["Fabulous Thunderbirds", ""],
    ["Fall Out Boy", "https://www.texreview.com/2015/12/fall-out-boy-in-austin-texas-december.html"],
    ["Falls", ""],
    ["Fat White Family", ""],
    ["Father John Misty", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-friday-2014.html"],
    ["Feed Her To the Sharks", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Firehouse", "https://www.texreview.com/2016/05/firehouse-performing-in-cedar-park-texas.html"],
    ["Fitz & The Tantrums", "https://www.texreview.com/2016/12/fitz-tantrums-performing-in-cedar-park.html"],
    ["Five Finger Death Punch", ""],
    ["Foreigner", "http://www.texreview.com/2018/02/foreigner-performing-at-acl-live-in.html"],
    ["Foster the People", ""],
    ["Frank Iero and the Patience", "https://www.texreview.com/2017/06/frank-iero-and-patience-performing-at.html"],
    ["Futuristic", ""],

    ["G3", "http://www.texreview.com/2018/01/joe-satriani-with-g3-2018-performing-at.html"],
    ["G-Eazy", "http://www.texreview.com/2018/02/g-eazy-performing-at-acl-live-moody.html"],
    ["Galactic Empire", "http://www.texreview.com/2018/03/galactic-empire-performing-at-come-and.html"],
    ["Ghost", "https://www.texreview.com/2016/04/ghost-performing-in-austin-texas.html"],
    ["Ginuwine", ""],
    ["Glassjaw", ""],
    ["Green Day", "http://www.texreview.com/2017/09/green-day-performing-at-at-center-in.html"],
    ["Guy Forsyth Band", ""],
    ["GWAR", ""],

    ["Halestorm", "https://www.texreview.com/2016/07/halestorm-performing-in-cedar-park.html"],
    ["Hayley Kiyoko", "https://www.texreview.com/2018/05/hayley-kiyoko-performing-at-emos-austin.html"],
    ["Hellyeah", "https://www.texreview.com/2016/05/hellyeah-performing-in-san-antonio-texas.html"],
    ["Hellzapoppin Circus Sideshow", "https://www.texreview.com/2018/01/hellzapoppin-performing-at-aztec.html"],
    ["Hikes", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Hogan & Moss", ""],
    ["Holiday Mountain", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Hundredth", ""],

    ["Iceage", ""],
    ["Iggy Azalea", ""],
    ["In This Moment", "https://www.texreview.com/2016/09/in-this-moment-performing-in-austin.html"],
    ["Incubus", "https://www.texreview.com/2017/08/incubus-performing-at-austin360.html"],
    ["Interpol", ""],
    ["IsoLayDead", ""],
    ["Issues", "https://www.texreview.com/2015/04/issues-performing-in-austin-texas.html"],

    ["J Balvin", ""],
    ["Jack Russell's Great White", "https://www.texreview.com/2016/05/jack-russells-great-white-performing-in.html"],
    ["James Bay", "https://www.texreview.com/2015/12/james-bay-in-austin-texas-december-17.html"],
    ["James Rivera (Metal Asylum)", ""],
    ["Jeff Beck", ""],
    ["Jello Biafra", ""],
    ["Jimmy Eat World", "https://www.texreview.com/2017/08/jimmy-eat-world-performing-at-austin360.html"],
    ["JJ Garrett Band", ""],
    ["Joe Bonamassa", "https://www.texreview.com/2018/05/joe-bonamassa-performing-at-acl-live.html"],
    ["Joe Satriani", "http://www.texreview.com/2018/01/joe-satriani-with-g3-2018-performing-at.html"],
    ["Joe Sumner", "https://www.texreview.com/2017/02/joe-sumner-performing-in-austin-texas.html"],
    ["John Garr", ""],
    ["John Petrucci", "http://www.texreview.com/2018/01/john-petrucci-with-g3-2018-performing.html"],
    ["Jose Ruiz & The Sweet Tones", ""],
    ["Journey", ""],
    ["Judas Priest", "https://www.texreview.com/2015/05/judas-priest-cedar-park-texas-may-14.html"],
    ["Jungle Rot", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],

    ["Kacey Musgraves", "http://www.texreview.com/2018/02/kacey-musgraves-performing-at-frank.html"],
    ["Kelly Clarkson", "https://www.texreview.com/2017/12/kelly-clarkson-performing-at-austin.html"],
    ["Kevin Finch", ""],
    ["Kid Rock", ""],
    ["Killswitch Engage", ""],
    ["King Diamond", "https://www.texreview.com/2014/11/king-diamond-fun-fun-fun-fest-austin.html"],
    ["Kissing Candice", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Korn", "https://www.texreview.com/2016/08/korn-performing-in-austin-texas.html"],
    ["KP and the Boom Boom", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-friday-2014.html"],

    ["Lake Street Drive", ""],
    ["Lamb of God", "https://www.texreview.com/2015/10/lamb-of-god-austin-texas-september-2.html"],
    ["Lindsey Stirling", "https://www.texreview.com/2016/11/lindsey-stirling-performing-in-austin.html"],
    ["Lisa Tingle", ""],
    ["Little Big Town", "http://www.texreview.com/2018/02/little-big-town-performing-at-frank.html"],
    ["Lizzy Borden", ""],
    ["Local H", "http://www.texreview.com/2017/06/local-h-performing-at-alamodome-in-san.html"],
    ["Lorde", ""],
    ["Lunice", ""],

    ["Mac DeMarco", "https://www.texreview.com/2017/10/mac-demarco-performing-at-acl-live.html"],
    ["Mac Sabbath", "http://www.texreview.com/2018/03/mac-sabbath-performing-at-come-and-take.html"],
    ["Major Lazer", ""],
    ["Makeout", "https://www.texreview.com/2017/03/makeout-performing-at-austin360.html"],
    ["Malford Milligan", ""],
    ["Marcia Ball", ""],
    ["Marian Hill", "https://www.texreview.com/2017/11/marian-hill-performing-at-acl-live.html"],
    ["Matchbox Twenty", "http://www.texreview.com/2017/10/matchbox-twenty-performing-at-heb.html"],
    ["Matt Nathanson", "http://www.texreview.com/2017/09/matt-nathanson-performing-at-heb-center.html"],
    ["Matt the Cat Trio", ""],
    ["Megadeth", "https://www.texreview.com/2016/05/megadeth-performing-in-san-antonio-texas.html"],
    ["Memphis May Fire", ""],
    ["Metallica", "http://www.texreview.com/2017/06/metallica-performing-at-alamodome-in.html"],
    ["METZ", ""],
    ["Middle Class Rut", ""],
    ["Midland", "http://www.texreview.com/2018/02/midland-performing-at-frank-erwin.html"],
    ["Mike Posner", "https://www.texreview.com/2016/09/mike-posner-performing-in-san-antonio.html"],
    ["Miss Lavelle White", ""],
    ["MisterWives", "https://www.texreview.com/2017/04/misterwives-performing-in-austin-texas.html"],
    ["Mo", ""],
    ["Monte Montgomery", ""],
    ["Motionless In White", "https://www.texreview.com/2015/10/motionless-in-white-austin-texas.html"],
    ["Municipal Waste", ""],

    ["Nancy Silva Project", "https://www.texreview.com/2015/10/nancy-silva-project-in-austin-texas.html"],
    ["Nashville Pussy", "https://www.texreview.com/2015/09/nashville-pussy-austin-texas-august-28.html"],
    ["New Years Day", ""],
    ["Nick Jonas", "https://www.texreview.com/2016/10/nick-jonas-performing-in-san-antonio.html"],
    ["Night Ranger", "https://www.texreview.com/2018/06/night-ranger-performing-at-acl-live.html"],
    ["Night Terrors of 1927", ""],
    ["Nostalghia", ""],
    ["Nothing", "https://www.texreview.com/2017/02/nothing-performing-in-austin-texas.html"],
    ["Nothing More", ""],

    ["Of Mice & Men", "http://www.texreview.com/2017/10/of-mice-men-performing-at-vibes-event.html"],
    ["One-Eyed Doll", "https://www.texreview.com/2015/03/one-eyed-doll-fitzgeralds-san-antonio.html"],
    ["Outkast", ""],
    ["Our Last Night", ""],

    ["Pallbearer", ""],
    ["Panic! At The Disco", "https://www.texreview.com/2017/04/panic-at-disco-performing-in-austin.html"],
    ["Peelander-Z", ""],
    ["Pentatonix", "https://www.texreview.com/2016/11/pentatonix-performing-in-houston-texas.html"],
    ["Phil Collen", "http://www.texreview.com/2018/01/phil-collen-with-g3-2018-performing-at.html"],
    ["Phora", "http://www.texreview.com/2018/02/phora-performing-at-acl-live-moody.html"],
    ["Pierce The Veil", "https://www.texreview.com/2017/04/pierce-veil-performing-at-acl-live-in.html"],
    ["PigWeed", "https://www.texreview.com/2015/12/pigweed-in-austin-texas-october-17-2015.html"],
    ["Pink Floyd Laser Spectacular", "https://www.texreview.com/2015/02/pink-floyd-laser-spectacular-frank.html"],
    ["Pitbull", "http://www.texreview.com/2017/06/pitbull-performing-at-at-center-in-san.html"],
    ["P.O.D.", "https://www.texreview.com/2017/04/pod-performing-at-fiesta-oyster-bake-in.html"],
    ["Poeta", ""],
    ["Pop Evil", "https://www.texreview.com/2016/05/pop-evil-performing-in-san-antonio-texas.html"],
    ["Poppy", "https://www.texreview.com/2017/11/poppy-performing-at-stubbs-in-austin.html"],
    ["Pretty Sister", "https://www.texreview.com/2018/06/pretty-sister-performing-at-stubbs.html"],
    ["Primus", ""],
    ["Pussy Factory", "https://www.texreview.com/2015/12/pussy-factory-in-austin-texas-october.html"],

    ["Rachel Platten", "https://www.texreview.com/2017/12/rachel-platten-performing-at-austin.html"],
    ["Radkey", ""],
    ["Rainbow Kitten Surprise", "https://www.texreview.com/2018/05/rainbow-kitten-surprise-performing-at.html"],
    ["Ranch Ghost", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-friday-2014.html"],
    ["Ratt", "https://www.texreview.com/2016/05/ratt-performing-in-cedar-park-texas.html"],
    ["Rebelution", ""],
    ["Red Sun Rising", "https://www.texreview.com/2017/04/red-sun-rising-performing-at-fiesta.html"],
    ["REO Speedwagon", "http://www.texreview.com/2017/07/reo-speedwagon-performing-at-heb-center.html"],
    ["Reputante", ""],
    ["Rise Against", "https://www.texreview.com/2017/06/rise-against-performing-at-austin360.html"],
    ["Rob Zombie", "https://www.texreview.com/2016/08/rob-zombie-performing-in-austin-texas.html"],
    ["Ruby Jane", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Rueben and the Dark", ""],
    ["Run 2 Cover", "https://www.texreview.com/2015/10/run-2-cover-in-austin-texas-20151017.html"],

    ["Saint Motel", "https://www.texreview.com/2017/04/saint-motel-performing-in-austin-texas.html"],
    ["San Antoinio Pipes & Drums", ""],
    ["San Fermin", ""],
    ["Scorpions", "https://www.texreview.com/2016/05/scorpions-performing-in-san-antonio.html"],
    ["Secondhand Serenade", "https://www.texreview.com/2017/12/secondhand-serenade-performing-at.html"],
    ["Seether", ""],
    ["Sevendust", "https://www.texreview.com/2016/05/sevendust-performing-in-san-antonio.html"],
    ["Shattered Sun", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Shelley King", ""],
    ["Sick Of It All", "https://www.texreview.com/2014/11/sick-of-it-all-fun-fun-fun-festival.html"],
    ["Sid Fly", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-friday-2014.html"],
    ["Shania Twain", "https://www.texreview.com/2018/06/shania-twain-performing-at-frank-erwin.html"],
    ["Shinedown", "https://www.texreview.com/2016/07/shinedown-performing-in-cedar-park.html"],
    ["Silverstein", ""],
    ["Siren", ""],
    ["Sixx:A.M.", "https://www.texreview.com/2016/05/sixxam-performing-in-san-antonio-texas.html"],
    ["Sister Sin", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Skillet", "https://www.texreview.com/2017/04/skillet-performing-at-fiesta-oyster.html"],
    ["Skrillex", ""],
    ["Slayer", "https://www.texreview.com/2014/11/slayer-acl-live-austin-texas-nov-18-2014.html"],
    ["Slipknot", "https://www.texreview.com/2015/10/slipknot-austin-texas-september-2-2015.html"],
    ["Snoop Dogg", "https://www.texreview.com/2017/12/snoop-dogg-performing-at-emos-in-austin.html"],
    ["Sonic Boom Six", ""],
    ["Sour Bridges", ""],
    ["Souvenirs", "https://www.texreview.com/2017/02/souvenirs-performing-in-austin-texas.html"],
    ["St. Vincent", "http://www.texreview.com/2018/02/st-vincent-performing-at-acl-live-moody.html"],
    ["Star & Micey", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Starset", "https://www.texreview.com/2016/04/starset-performing-in-austin-texas.html"],
    ["SteelHeart", "https://www.texreview.com/2016/05/steelheart-performing-in-cedar-park.html"],
    ["Steve Miller Band", ""],
    ["Stevie Nicks", "https://www.texreview.com/2017/03/stevie-nicks-performing-at-frank-erwin.html"],
    ["Sting", "https://www.texreview.com/2017/02/sting-performing-in-austin-texas.html"],
    ["Stitched Up Heart", "https://www.texreview.com/2015/10/stitched-up-heart-in-austin-texas.html"],
    ["Styx", "http://www.texreview.com/2017/07/styx-performing-at-heb-center-at-cedar.html"],
    ["Sucka Please", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-friday-2014.html"],
    ["Suicidal Tendencies", ""],
    ["Sum 41", "https://www.texreview.com/2017/04/sum-41-performing-in-austin-texas.html"],
    ["Sun Kil Moon", ""],
    ["Superfruit", "https://www.texreview.com/2018/06/superfruit-performing-at-stubbs-indoors.html"],
    ["Sworn In", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],

    ["Tejas Brothers", "http://www.texreview.com/2017/09/tenacious-d-performing-at-stubbs-in.html"],
    ["Tenacious D", "http://www.texreview.com/2017/09/tenacious-d-performing-at-stubbs-in.html"],
    ["Tesla", "https://www.texreview.com/2017/03/tesla-performing-in-austin-texas.html"],
    ["Texas Hippie Coalition", "https://www.texreview.com/2015/05/texas-hippie-coalition-cedar-park-texas.html"],
    ["Temples", ""],
    ["The Akuzma", ""],
    ["The All-American Rejects", "https://www.texreview.com/2016/07/the-all-american-rejects-performing-in.html"],
    ["The Answer", "https://www.texreview.com/2015/09/the-answer-san-antonio-texas-june-23.html"],
    ["The Avett Brothers", ""],
    ["The Band Perry", "https://www.texreview.com/2015/12/the-band-perry-in-austin-texas-december.html"],
    ["The Beans", "https://www.texreview.com/2017/04/the-beans-performing-at-fiesta-oyster.html"],
    ["The Brains", "https://www.texreview.com/2018/01/the-brains-performing-at-aztec-theatre.html"],
    ["The Cringe", "https://www.texreview.com/2017/03/the-cringe-performing-in-austin-texas.html"],
    ["The Devil Wears Prada", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["The Federal Empire", "https://www.texreview.com/2016/11/the-federal-empire-performing-in-austin.html"],
    ["The Flaming Lips", "https://www.texreview.com/2017/10/the-flaming-lips-performing-at-acl-live.html"],
    ["The Garden", "https://www.texreview.com/2017/10/the-garden-performing-at-acl-live-moody.html"],
    ["The Gaslight Anthem", ""],
    ["The Glitch Mob", ""],
    ["The Last Bandoleros", "https://www.texreview.com/2017/02/the-last-bandoleros-performing-in.html"],
    ["The Naked and Famous", "https://www.texreview.com/2017/03/the-naked-and-famous-performing-at.html"],
    ["The New Pornographers", ""],
    ["The Night Of", ""],
    ["The Other LA", "http://www.texreview.com/2017/10/the-other-la-performing-at-rock-box-in.html"],
    ["The Pains of Being Pure At Heart", ""],
    ["The Pretenders", "https://www.texreview.com/2017/03/chrissie-hynde-with-pretenders.html"],
    ["The Preatures", ""],
    ["The Replacements", ""],
    ["The Stapletones", ""],
    ["The Sword", "https://www.texreview.com/2016/05/the-sword-performing-in-san-antonio.html"],
    ["Thrice", "https://www.texreview.com/2017/06/thrice-performing-at-austin360.html"],
    ["Thy Art Is Murder", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Toby Keith", "https://www.texreview.com/2015/04/toby-keith-austin-texas-apr-16-2015.html"],
    ["Tom Keifer", "https://www.texreview.com/2018/04/tom-keifer-performing-at-fiesta-oyster.html"],
    ["Train", "https://www.texreview.com/2016/12/train-performing-in-cedar-park-texas.html"],
    ["Trans-Siberian Orchestra", "https://www.texreview.com/2017/12/trans-siberian-orchestra-performing-at.html"],
    ["Tribulation", "https://www.texreview.com/2016/04/tribulation-performing-in-austin-texas.html"],
    ["Trippie Redd", "http://www.texreview.com/2018/02/trippie-redd-performing-at-acl-live.html"],
    ["Trixter", "https://www.texreview.com/2017/03/trixter-performing-in-san-antonio-texas.html"],
    ["Twin Peaks", ""],
    ["Tyler Bryant", "https://www.texreview.com/2015/04/tyler-bryant-cedar-park-texas-april-30.html"],
    ["Tuck & Patti", "http://www.texreview.com/2018/02/tuck-patti-performing-at-acl-live-moody.html"],
    ["tUnE-yArDs", ""],

    ["Us The Duo", "https://www.texreview.com/2016/11/us-duo-performing-in-houston-texas.html"],

    ["Vagenda", "https://www.texreview.com/2015/03/vagenda-fitzgeralds-san-antonio-texas.html"],
    ["Vallejo", ""],
    ["Valient Thorr", "https://www.texreview.com/2015/09/valient-thorr-austin-texas-august-28.html"],
    ["Veridia", "https://www.texreview.com/2016/11/veridia-performing-in-austin-texas.html"],
    ["von Grey", ""],

    ["Walk The Moon", "http://www.texreview.com/2018/02/walk-moon-performing-at-acl-live-moody.html"],
    ["Wall of Soul", ""],
    ["Warpaint", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Warrant", "https://www.texreview.com/2017/03/warrant-performing-in-san-antonio-texas.html"],
    ["Wheeler Brothers", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-friday-2014.html"],
    ["Whiskey Myers", "https://www.texreview.com/2016/07/whiskey-myers-performing-in-cedar-park.html"],
    ["Whitechapel", "https://www.texreview.com/2015/07/mayhem-festival-in-san-antonio-texas.html"],
    ["Whitesnake", "https://www.texreview.com/2016/06/whitesnake-performing-in-san-antonio.html"],
    ["Whitford / St.Holmes", "https://www.texreview.com/2016/06/whitford-st-holmes-performing-in-san.html"],
    ["Wild Child", "https://www.texreview.com/2014/09/utopiafest-in-utopia-texas-saturday.html"],
    ["Willie Nelson", ""],
    ["Wood & Wire", ""],

    ["Yelle", ""],

    ["Zella Day", "https://www.texreview.com/2015/12/zella-day-in-austin-texas-december-17.html"],
    ["Zorch", ""],
    ["ZZ Top", "https://www.texreview.com/2015/01/zz-top-majestic-theater-san-antonio.html"]
    ];
}

