
function GetBandList() {
    return [
    ["A Day To Remember", "http://www.texreview.com/2016/07/a-day-to-remember-performing-at-at.html"],
    ["Abi Ann", "http://www.texreview.com/2016/11/abi-ann-performing-in-houston-texas.html"],
    ["Above My Enemy", ""],
    ["All Sides Equal", "http://www.texreview.com/2015/03/all-sides-equal-fitzgeralds-san-antonio.html"],
    ["AFI (A Fire Inside)", ""],
    ["AJ Lehrman", "http://www.texreview.com/2016/05/aj-lehrman-performing-in-austin-texas.html"],
    ["Alice Cooper", "http://www.texreview.com/2015/02/alice-cooper-majestic-theater-san.html"],
    ["Amon Amarth", ""],
    ["Annalise Emerick", ""],
    ["Ashley Cleveland", ""],
    ["Ashley Monical", ""],
    ["Asleep at the Wheel", ""],

    ["Barton Hills Choir", ""],
    ["Benjamin Booker", ""],
    ["Benji Hughes", ""],
    ["Billy Joe Shaver", ""],
    ["Black Heart Saints", "http://www.texreview.com/2015/10/black-heart-saints-in-austin-texas.html"],
    ["Black Label Society", ""],
    ["Black Lips", ""],
    ["Black Pistol Fire", ""],
    ["Black Stone Cherry", "http://www.texreview.com/2016/07/black-stone-cherry-performing-in-cedar.html"],
    ["Blake Richardson Band", ""],
    ["blink-182", "http://www.texreview.com/2016/07/blink-182-performing-in-san-antonio.html"],
    ["Blue, The Misfit", ""],
    ["Blue October", "http://www.texreview.com/2016/12/blue-october-performing-in-cedar-park.html"],
    ["Borrisokane", ""],
    ["Boston", "http://www.texreview.com/2016/06/boston-performing-in-austin-texas.html"],
    ["Breakout", ""],
    ["Bret Michaels", "http://www.texreview.com/2016/05/bret-michaels-performing-in-cedar-park.html"],
    ["Broods", ""],
    ["Bullet For My Valentine", "http://www.texreview.com/2015/10/bullet-for-my-valentine-austin-texas.html"],
    ["Butcher Babies", ""],

    ["Calvin Harris", ""],
    ["Canvas People", ""],
    ["Capital Cities", ""],
    ["Carolyn Wonderland", ""],
    ["Celeste'al Descent", ""],
    ["Charlie Pierce", ""],
    ["Chris Castaneda Project", ""],
    ["Chromeo", ""],
    ["Chvrches", ""],
    ["Cilantro Boombox", ""],
    ["City and Colour", ""],
    ["Communion", ""],
    ["Courtney Barnett", ""],
    ["Crooks", ""],
    ["Cults", ""],

    ["Dave Sebree", ""],
    ["Deftones", ""],
    ["Del Castillo", ""],
    ["Demi Lovato", "http://www.texreview.com/2016/09/demi-lovato-performing-in-san-antonio.html"],

    ["Evanescence", "http://www.texreview.com/2016/11/evanescence-performing-in-austin-texas.html"],
    ["Emily Wolfe", ""],
    ["Enrique Iglesias", "http://www.texreview.com/2015/02/enrique-iglesias-frank-erwin-center.html"],
    ["Eric Hutchinson", "http://www.texreview.com/2015/09/eric-hutchinson-austin-texas-august-29.html"],
    ["Eric Tessmer", ""],
    ["Exodus", ""],
    ["Eye of Time", ""],

    ["Fabulous Thunderbirds", ""],
    ["Fall Out Boy", "http://www.texreview.com/2015/12/fall-out-boy-in-austin-texas-december.html"],
    ["Falls", ""],
    ["Fat White Family", ""],
    ["Father John Misty", ""],
    ["Firehouse", "http://www.texreview.com/2016/05/firehouse-performing-in-cedar-park-texas.html"],
    ["Fitz & The Tantrums", "http://www.texreview.com/2016/12/fitz-tantrums-performing-in-cedar-park.html"],
    ["Five Finger Death Punch", ""],
    ["Foster the People", ""],

    ["Ghost", "http://www.texreview.com/2016/04/ghost-performing-in-austin-texas.html"],
    ["Ginuwine", ""],
    ["Glassjaw", ""],
    ["Guy Forsyth Band", ""],

    ["Halestorm", "http://www.texreview.com/2016/07/halestorm-performing-in-cedar-park.html"],
    ["Hellyeah", ""],
    ["Hikes", ""],
    ["Hogan & Moss", ""],
    ["Holiday Mountain", ""],

    ["Iceage", ""],
    ["Iggy Azalea", ""],
    ["In This Moment", "http://www.texreview.com/2016/09/in-this-moment-performing-in-austin.html"],
    ["Interpol", ""],
    ["IsoLayDead", ""],

    ["J Balvin", ""],
    ["Jack Russell's Great White", "http://www.texreview.com/2016/05/jack-russells-great-white-performing-in.html"],
    ["James Bay", "http://www.texreview.com/2015/12/james-bay-in-austin-texas-december-17.html"],
    ["James Rivera (Metal Asylum)", ""],
    ["Jeff Beck", ""],
    ["Jello Biafra", ""],
    ["JJ Garrett Band", ""],
    ["John Garr", ""],
    ["Jose Ruiz & The Sweet Tones", ""],
    ["Journey", ""],
    ["Judas Priest", "http://www.texreview.com/2015/05/judas-priest-cedar-park-texas-may-14.html"],

    ["Kelly Clarkson", "http://www.texreview.com/2015/09/kelly-clarkson-austin-texas-august-29.html"],
    ["Kevin Finch", ""],
    ["Kid Rock", ""],
    ["Killswitch Engage", ""],
    ["King Diamond", "http://www.texreview.com/2014/11/king-diamond-fun-fun-fun-fest-austin.html"],
    ["Korn", "http://www.texreview.com/2016/08/korn-performing-in-austin-texas.html"],
    ["KP and the Boom Boom", ""],

    ["Lake Street Drive", ""],
    ["Lamb of God", "http://www.texreview.com/2015/10/lamb-of-god-austin-texas-september-2.html"],
    ["Lindsey Stirling", "http://www.texreview.com/2016/11/lindsey-stirling-performing-in-austin.html"],
    ["Lisa Tingle", ""],
    ["Little Big Town", "http://www.texreview.com/2015/04/little-big-town-austin-texas-apr-16-205.html"],
    ["Lizzy Borden", ""],
    ["Lorde", ""],
    ["Lunice", ""],

    ["Mac DeMarco", ""],
    ["Major Lazer", ""],
    ["Malford Milligan", ""],
    ["Marcia Ball", ""],
    ["Matt Nathanson", ""],
    ["Matt the Cat Trio", ""],
    ["Metallica", "http://www.texreview.com/2015/06/metallica-austin-texas-june-6-2015.html"],
    ["METZ", ""],
    ["Middle Class Rut", ""],
    ["Mike Posner", "http://www.texreview.com/2016/09/mike-posner-performing-in-san-antonio.html"],
    ["Miss Lavelle White", ""],
    ["Mo", ""],
    ["Monte Montgomery", ""],
    ["Motionless In White", "http://www.texreview.com/2015/10/motionless-in-white-austin-texas.html"],
    ["Nancy Silva Project", "http://www.texreview.com/2015/10/nancy-silva-project-in-austin-texas.html"],

    ["Nashville Pussy", "http://www.texreview.com/2015/09/nashville-pussy-austin-texas-august-28.html"],
    ["Nick Jonas", "http://www.texreview.com/2016/10/nick-jonas-performing-in-san-antonio.html"],
    ["Night Terrors of 1927", ""],
    ["Nostalghia", ""],
    ["Nothing More", ""],

    ["One-Eyed Doll", "http://www.texreview.com/2015/03/one-eyed-doll-fitzgeralds-san-antonio.html"],
    ["Outkast", ""],

    ["Pallbearer", ""],
    ["Peelander-Z", ""],
    ["Pentatonix", "http://www.texreview.com/2016/11/pentatonix-performing-in-houston-texas.html"],
    ["PigWeed", "http://www.texreview.com/2015/12/pigweed-in-austin-texas-october-17-2015.html"],
    ["Pink Floyd Laser Spectacular", "http://www.texreview.com/2015/02/pink-floyd-laser-spectacular-frank.html"],
    ["Pitbull", "http://www.texreview.com/2015/02/pitbull-frank-erwin-center-austin-texas.html"],
    ["Primus", ""],
    ["Pussy Factory", "http://www.texreview.com/2015/12/pussy-factory-in-austin-texas-october.html"],

    ["Radkey", ""],
    ["Ranch Ghost", ""],
    ["Ratt", "http://www.texreview.com/2016/05/ratt-performing-in-cedar-park-texas.html"],
    ["Rebelution", ""],
    ["Reputante", ""],
    ["Rob Zombie", "http://www.texreview.com/2016/08/rob-zombie-performing-in-austin-texas.html"],
    ["Ruby Jane", ""],
    ["Rueben and the Dark", ""],
    ["Run 2 Cover", "http://www.texreview.com/2015/10/run-2-cover-in-austin-texas-20151017.html"],

    ["San Antoinio Pipes & Drums", ""],
    ["San Fermin", ""],
    ["Seether", ""],
    ["Shelley King", ""],
    ["Sick Of It All", "http://www.texreview.com/2014/11/sick-of-it-all-fun-fun-fun-festival.html"],
    ["Sid Fly", ""],
    ["Shinedown", "http://www.texreview.com/2016/07/shinedown-performing-in-cedar-park.html"],
    ["Siren", ""],
    ["Skrillex", ""],
    ["Slayer", "http://www.texreview.com/2014/11/slayer-acl-live-austin-texas-nov-18-2014.html"],
    ["Slipknot", "http://www.texreview.com/2015/10/slipknot-austin-texas-september-2-2015.html"],
    ["Sour Bridges", ""],
    ["St. Vincent", ""],
    ["Star & Micey", ""],
    ["Starset", "http://www.texreview.com/2016/04/starset-performing-in-austin-texas.html"],
    ["SteelHeart", "http://www.texreview.com/2016/05/steelheart-performing-in-cedar-park.html"],
    ["Steve Miller Band", ""],
    ["Stitched Up Heart", "http://www.texreview.com/2015/10/stitched-up-heart-in-austin-texas.html"],
    ["Sucka Please", ""],
    ["Sun Kil Moon", ""],
    ["Suicidal Tendencies", ""],

    ["Tejas Brothers", ""],
    ["Texas Hippie Coalition", "http://www.texreview.com/2015/05/texas-hippie-coalition-cedar-park-texas.html"],
    ["Temples", ""],
    ["The Akuzma", ""],
    ["The All-American Rejects", "http://www.texreview.com/2016/07/the-all-american-rejects-performing-in.html"],
    ["The Answer", "http://www.texreview.com/2015/09/the-answer-san-antonio-texas-june-23.html"],
    ["The Avett Brothers", ""],
    ["The Band Perry", "http://www.texreview.com/2015/12/the-band-perry-in-austin-texas-december.html"],
    ["The Federal Empire", "http://www.texreview.com/2016/11/the-federal-empire-performing-in-austin.html"],
    ["The Gaslight Anthem", ""],
    ["The Glitch Mob", ""],
    ["The New Pornographers", ""],
    ["The Pains of Being Pure At Heart", ""],
    ["The Preatures", ""],
    ["The Replacements", ""],
    ["The Stapletones", ""],
    ["Toby Keith", "http://www.texreview.com/2015/04/toby-keith-austin-texas-apr-16-2015.html"],
    ["Train", "http://www.texreview.com/2016/12/train-performing-in-cedar-park-texas.html"],
    ["Trans-Siberian Orchestra", "http://www.texreview.com/2015/12/trans-siberian-orchestra-in-austin.html"],
    ["Tribulation", "http://www.texreview.com/2016/04/tribulation-performing-in-austin-texas.html"],
    ["Twin Peaks", ""],
    ["Tyler Bryant", "http://www.texreview.com/2015/09/tyler-bryant-cedar-park-texas-april-30.html"],
    ["tUnE-yArDs", ""],

    ["Us The Duo", "http://www.texreview.com/2016/11/us-duo-performing-in-houston-texas.html"],

    ["Vagenda", "http://www.texreview.com/2015/03/vagenda-fitzgeralds-san-antonio-texas.html"],
    ["Vallejo", ""],
    ["Valient Thorr", "http://www.texreview.com/2015/09/valient-thorr-austin-texas-august-28.html"],
    ["Veridia", "http://www.texreview.com/2016/11/veridia-performing-in-austin-texas.html"],
    ["von Grey", ""],

    ["Wall of Soul", ""],
    ["Warpaint", ""],
    ["Warrant", "http://www.texreview.com/2016/05/warrant-performing-in-cedar-park-texas.html"],
    ["Wheeler Brothers", ""],
    ["Whiskey Myers", "http://www.texreview.com/2016/07/whiskey-myers-performing-in-cedar-park.html"],
    ["Whitford / St.Holmes", "http://www.texreview.com/2016/06/whitford-st-holmes-performing-in-san.html"],
    ["Whitesnake", "http://www.texreview.com/2016/06/whitesnake-performing-in-san-antonio.html"],
    ["Wild Child", ""],
    ["Willie Nelson", ""],
    ["Wood & Wire", ""],

    ["Yelle", ""],

    ["Zella Day", "http://www.texreview.com/2015/12/zella-day-in-austin-texas-december-17.html"],
    ["Zorch", ""],
    ["ZZ Top", "http://www.texreview.com/2015/01/zz-top-majestic-theater-san-antonio.html"]
    ];
}
